### ISSUE TITLE
Cygwin tar interferes with cache action on Windows

### ISSUE THREAD

**Issue by mnxn** [avsm/setup-ocaml#54] opened 2021-01-20 09:37 UTC
On Windows, setup-ocaml adds the `c:\cygwin\bin` directory to the PATH: https://github.com/avsm/setup-ocaml/blob/d3953534ca55051a028ce12a39f9fe4f15035f8d/src/installer.ts#L51

This directory contains a lot of programs that are intended to be used from a Cygwin environment and don't work from the Windows environment. One such program is `tar`, which causes the cache action to fail (encountered in https://github.com/ocamllabs/vscode-ocaml-platform/pull/501):

```
Post job cleanup.
c:\cygwin\bin\tar.exe --posix --use-compress-program "zstd -T0" -cf cache.tzst -P -C D:/a/vscode-ocaml-platform/vscode-ocaml-platform --files-from manifest.txt --force-local
/usr/bin/tar: C\:\\cygwin\\home\runneradmin\\.opam: Cannot stat: No such file or directory
/usr/bin/tar: Exiting with failure status due to previous errors
Warning: Tar failed with error: The process 'c:\cygwin\bin\tar.exe' failed with exit code 2
```

Is there a reason this directory is being added to the PATH? I think only adding `c:\cygwin\wrapperbin` would be enough.

**Comment by dra27** [comment] 2021-01-20 09:52
Just for the proverbial record, the programs do work - the issue is that Cygwin's `tar` doesn't translate DOS filenames (see, for example, https://github.com/ocaml/opam/commit/5684fd56591ee0ec6f5c3406eb23c9dda78a0dcf

The issue is the `core.addPath` prepends its arguments - it would be much better for the `bin` directory to be being appended. The `bin` directory is needed for commands like `x86_64-w64-mingw32-gcc` as well as more mundane things such as opam packages using `cp`, `mv`, etc. (all of which do interpret Cygwin paths correctly).

**Comment by dra27** [comment] 2021-01-20 09:55
I'm not sure that this works with Windows `tar` either, as bsdtar 3.3.2 doesn't support those arguments either...

**Comment by smorimoto** [comment] 2021-01-20 18:08
I've been aware of this for quite some time and have been working with the Actions team on things to address. (The cache action uses zstd, so there are some tricky points, mainly about which tar to use...)

**Comment by smorimoto** [comment] 2021-01-27 07:02
This is not a issue with setup-ocaml, but with actions/toolkit, so I will close this. See this for more details: https://github.com/actions/toolkit/pull/610

**Closed by smorimoto** 2021-01-27 07:02 UTC
